import { Home, Search, PlusCircle, Compass, User, Settings, Bell, MessagesSquare, ArrowLeft, Palette, Trash, Plus, Edit, Heart, Share2, MessageCircle, Bookmark, Info, Loader2, Volume2, Volume, Image, Type } from "lucide-react";

export const Icons = {
  home: Home,
  search: Search,
  plusCircle: PlusCircle,
  compass: Compass,
  user: User,
  settings: Settings,
  bell: Bell,
  messages: MessagesSquare,
  arrowLeft: ArrowLeft,
  palette: Palette,
  plus: Plus,
  trash: Trash,
  edit: Edit,
  heart: Heart,
  comment: MessageCircle,
  save: Bookmark,
  share: Share2,
  info: Info,
  loader: Loader2,
  volume2: Volume2,
  volume: Volume,
  image: Image,
  type: Type,
};